AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Firehose for data collection

Parameters:
  Name:
    Type: String
  Stage:
    Type: String

Resources:
  DataBucket:
    Type: AWS::S3::Bucket

  Firehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      ExtendedS3DestinationConfiguration:
        BucketARN:
          Fn::GetAtt: [ DataBucket, Arn ]
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 10
        CompressionFormat: UNCOMPRESSED
        Prefix: "raw/ga/year=!{timestamp:YYYY}/month=!{timestamp:MM}/day=!{timestamp:dd}/"
        ErrorOutputPrefix: "errors/!{firehose:random-string}/!{firehose:error-output-type}/!{timestamp:yyyy/MM/dd}/"
        RoleARN:
          Fn::GetAtt: [ KinesisFirehoseRole, Arn ]
          #        ProcessingConfiguration:
          #          Enabled: true
          #          Processors:
          #            - Parameters:
          #              - ParameterName: LambdaArn
          #                ParameterValue: 
          #                  Fn::GetAtt: [FirehoseTransformationFunction, Arn]
          #              Type: Lambda

  KinesisFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - firehose.amazonaws.com
          Action:
          - sts:AssumeRole

  S3DeliveryPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: firehose_s3delivery_policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
            Resource:
              - Fn::GetAtt: [ DataBucket , Arn ]
              - Fn::Join:
                - ""
                - - Fn::GetAtt: [ DataBucket , Arn ]
                  - "/*"
      Roles:
        - Ref: KinesisFirehoseRole

  FirehoseName:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub: '/applications/pipes/${Stage}/firehose/name'
      Type: String
      Value: 
        Ref: Firehose
