AWSTemplateFormatVersion: 2010-09-09
Outputs:
  ApiId:
    Description: The ID for the API in order to construct the tracking endpoint
    Export:
      Name: Pipesdata-ApiId
    Value:
      Ref: ApiGatewayRestApi
  ApiKey:
    Description: The Path of the POST endpoint in order to construct the tracking
      endpoint
    Export:
      Name: Pipesdata-ApiKey
    Value: no-key
  ApiPath:
    Description: The Path of the POST endpoint in order to construct the tracking
      endpoint
    Export:
      Name: Pipesdata-ApiPath
    Value:
      Fn::Sub: ${Stage}/com.pipesdata/v1
  ApiRegion:
    Description: The Region of the API in order to construct the tracking endpoint
    Export:
      Name: Pipesdata-ApiRegion
    Value:
      Ref: AWS::Region
  ApiStage:
    Description: The Stage of the API in order to construct the tracking endpoint
    Export:
      Name: Pipesdata-ApiStage
    Value:
      Ref: Stage
Parameters:
  AdminEmail:
    Default: dimitri+pipes@tarasowski.de
    Type: String
  FallbackEmail:
    Default: dimitri+pipes2@tarasowski.de
    Type: String
  Name:
    Default: PipesAPI
    Type: String
  S3AlarmPeriod:
    Default: 60
    Type: String
  Stage:
    Default: dev
    Type: String
Resources:
  ApiGatewayDeployment:
    DependsOn:
    - ApiGatewayPostMethod
    Properties:
      RestApiId:
        Ref: ApiGatewayRestApi
      StageName:
        Fn::Sub: ${Stage}
    Type: AWS::ApiGateway::Deployment
  ApiGatewayPostMethod:
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        Credentials:
          Fn::GetAtt:
          - GatewayRole
          - Arn
        IntegrationHttpMethod: POST
        IntegrationResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
            method.response.header.Access-Control-Allow-Methods: '''POST,OPTIONS'''
            method.response.header.Access-Control-Allow-Origin: '''*'''
          ResponseTemplates:
            application/json: '{"status":"OK"}'
          StatusCode: 200
        PassthroughBehavior: NEVER
        RequestParameters:
          integration.request.header.Content-Type: '''application/x-amz-json-1.1'''
        RequestTemplates:
          application/json:
            Fn::Sub: "#set( $system_source = \"system_source\")\n#set( $system_source_val\
              \ = \"ga\")\n#set( $system_version = \"system_version\")\n#set( $system_version_val\
              \ = \"1\")\n#set( $trace_id_val = $input.params().get(\"header\").get(\"\
              X-Amzn-Trace-Id\"))\n#set( $bodyname = \"body\" )\n#set( $trace_id =\
              \ \"trace_id\")\n#set( $received_at_apig = \"received_at_apig\")\n#set(\
              \ $received_at_apig_val = $context.requestTimeEpoch)\n#set( $body =\
              \ \"body\")\n#set( $body_val = $input.body)\n#set( $message_id = \"\
              message_id\")\n#set( $message_id_val = $context.requestId)\n#set( $ip\
              \ = \"ip\")\n#set( $ip_val = $context.identity.sourceIp)\n#set( $user_agent\
              \ = \"user_agent\")\n#set( $user_agent_val = $context.identity.userAgent)\n\
              #set( $quote = '\"' )\n#set( $b64 = $util.base64Encode(\"{$quote$system_source$quote:$quote$system_source_val$quote,$quote$system_version$quote:$quote$system_version_val$quote,$quote$message_id$quote:$quote$message_id_val$quote,$quote$trace_id$quote:$quote$trace_id_val$quote,$quote$received_at_apig$quote:$quote$received_at_apig_val$quote,$quote$ip$quote:$quote$ip_val$quote,\
              \ $quote$user_agent$quote:$quote$user_agent_val$quote,$quote$body$quote:$quote$body_val$quote}\"\
              ))\n{\n \"DeliveryStreamName\": \"${EventFirehose}\", \n \"Record\"\
              : {\"Data\": \"$b64\"}\n}\n"
        Type: AWS
        Uri:
          Fn::Join:
          - ''
          - - 'arn:aws:apigateway:'
            - Ref: AWS::Region
            - :firehose:action/PutRecord
      MethodResponses:
      - ResponseParameters:
          method.response.header.Access-Control-Allow-Headers: true
          method.response.header.Access-Control-Allow-Methods: true
          method.response.header.Access-Control-Allow-Origin: true
        StatusCode: 200
      ResourceId:
        Ref: GoogleAnalyticsVersion
      RestApiId:
        Ref: ApiGatewayRestApi
    Type: AWS::ApiGateway::Method
  ApiGatewayRestApi:
    Properties:
      Name:
        Fn::Join:
        - ''
        - - Ref: AWS::StackName
          - -api
    Type: AWS::ApiGateway::RestApi
  DataBucket:
    Type: AWS::S3::Bucket
  EventFirehose:
    Properties:
      ExtendedS3DestinationConfiguration:
        BucketARN:
          Fn::GetAtt:
          - DataBucket
          - Arn
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 10
        CompressionFormat: UNCOMPRESSED
        ErrorOutputPrefix: errors/!{firehose:random-string}/!{firehose:error-output-type}/!{timestamp:yyyy/MM/dd}/
        Prefix: raw/ga/year=!{timestamp:YYYY}/month=!{timestamp:MM}/day=!{timestamp:dd}/
        RoleARN:
          Fn::GetAtt:
          - KinesisFirehoseRole
          - Arn
    Type: AWS::KinesisFirehose::DeliveryStream
  GatewayRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - firehose:PutRecord
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: GatewayRolePolicy
    Type: AWS::IAM::Role
  GoogleAnalyticsResource:
    Properties:
      ParentId:
        Fn::GetAtt:
        - ApiGatewayRestApi
        - RootResourceId
      PathPart: com.pipesdata
      RestApiId:
        Ref: ApiGatewayRestApi
    Type: AWS::ApiGateway::Resource
  GoogleAnalyticsVersion:
    Properties:
      ParentId:
        Ref: GoogleAnalyticsResource
      PathPart: v1
      RestApiId:
        Ref: ApiGatewayRestApi
    Type: AWS::ApiGateway::Resource
  KinesisFirehoseRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - firehose.amazonaws.com
        Version: '2012-10-17'
    Type: AWS::IAM::Role
  OptionsMethod:
    Properties:
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
            method.response.header.Access-Control-Allow-Methods: '''POST,OPTIONS'''
            method.response.header.Access-Control-Allow-Origin: '''*'''
          ResponseTemplates:
            application/json: ''
          StatusCode: 200
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - ResponseModels:
          application/json: Empty
        ResponseParameters:
          method.response.header.Access-Control-Allow-Headers: false
          method.response.header.Access-Control-Allow-Methods: false
          method.response.header.Access-Control-Allow-Origin: false
        StatusCode: 200
      ResourceId:
        Ref: GoogleAnalyticsVersion
      RestApiId:
        Ref: ApiGatewayRestApi
    Type: AWS::ApiGateway::Method
  S3DeliveryPolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - s3:AbortMultipartUpload
          - s3:GetBucketLocation
          - s3:GetObject
          - s3:ListBucket
          - s3:ListBucketMultipartUploads
          - s3:PutObject
          Effect: Allow
          Resource:
          - Fn::GetAtt:
            - DataBucket
            - Arn
          - Fn::Join:
            - ''
            - - Fn::GetAtt:
                - DataBucket
                - Arn
              - /*
        Version: '2012-10-17'
      PolicyName: firehose_s3delivery_policy
      Roles:
      - Ref: KinesisFirehoseRole
    Type: AWS::IAM::Policy
Transform: AWS::Serverless-2016-10-31
