version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
      - pip install --upgrade awscli
      - echo "Current working directory"
      - pwd
      - cd ./functions/apig-validator/
      - npm i --production
      - cd ../../
      - echo "Dependencies install completed `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - aws cloudformation package --template-file cloudformation/main.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file app-output_sam.yaml
      - echo "Ending build `date` in `pwd`"
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - app-output_sam.yaml
  discard-paths: yes
